version: '3'
services:
    mysql:
        image: mysql:5.7
        network_mode: host
        container_name: mysql
        volumes:
            - $HOME/var/lib:/var/lib/mysql
        environment:
            - MYSQL_ROOT_PASSWORD:root
            - MYSQL_ROOT_HOST:%

    mongo:
        image: mongo:3.4-xenial
        network_mode: host
        container_name: mongo
        volumes:
            - /usr/src:/data/db

    eureka:
        image: eureka-service:1.0
        network_mode: host
        container_name: eureka
        build: eureka-service/

    config:
        image: config-server:1.0
        network_mode: host
        container_name: config-server
        build: config-server/

    movie:
        image: movie-service:1.0
        network_mode: host
        container_name: movie
        depends_on:
            - mongo
            - eureka
            - config
        build: movie-service/

    user:
        image: user-service:1.0
        network_mode: host
        container_name: user
        depends_on:
            - mysql
            - eureka
            - config
        build: user-service/

    api-gateway:
        image: api-gateway:1.0
        ports:
            - 8080:8080
        network_mode: host
        container_name: api-gateway
        expose:
            - 8080
        depends_on:
            - movie
            - user
            - eureka
        build:  api-gateway/